(function (cp) {
  const acidBaseList = {
    strongAcids: [
      {
        name: "Hydrochloric Acid",
        formula: "HCl",
        conjugate: "Cl<SUP>-</SUP>",
        K: 1,
        type: 1,
      },
      {
        name: "Hydroiodic Acid",
        formula: "HI",
        conjugate: "I<SUP>-</SUP>",
        K: 1,
        type: 1,
      },
      {
        name: "Hydrobromic Acid",
        formula: "HBr",
        conjugate: "Br<SUP>-</SUP>",
        K: 1,
        type: 1,
      },
      {
        name: "Perchloric Acid",
        formula: "HClO<SUB>4 </SUB>",
        conjugate: "ClO<SUB>4</SUB><SUP>-</SUP>",
        K: 1,
        type: 1,
      },
      {
        name: "Nitric Acid",
        formula: "HNO<SUB>3</SUB>",
        conjugate: "NO<SUB>3</SUB><SUP>-</SUP>",
        K: 1,
        type: 1,
      },
    ],
    weakAcids: [
      {
        name: "Acetic Acid",
        formula: "CH<SUB>3</SUB>COOH",
        conjugate: "CH<SUB>3</SUB>COO<SUP>-</SUP>",
        K: 1.8e-5,
        type: 2,
      },
      {
        name: "Acrylic Acid ",
        formula: "C<SUB>3</SUB>H<SUB>4</SUB>O<SUB>2</SUB>",
        conjugate: "C<SUB>3</SUB>H<SUB>3</SUB>O<SUB>2</SUB><SUP>-</SUP>",
        K: 5.5e-5,
        type: 2,
      },
      {
        name: "Benzoic Acid",
        formula: "C<SUB>7</SUB>H<SUB>6</SUB>O<SUB>2</SUB>",
        conjugate: "C<SUB>7</SUB>H<SUB>5</SUB>O<SUB>2</SUB><SUP>-</SUP>",
        K: 6.3e-5,
        type: 2,
      },
      {
        name: "Chloroacetic Acid",
        formula: "C<SUB>2</SUB>H<SUB>3</SUB>ClO<SUB>2</SUB>",
        conjugate: "C<SUB>2</SUB>H<SUB>2</SUB>ClO<SUB>2</SUB><SUP>-</SUP>",
        K: 1.4e-3,
        type: 2,
      },
      {
        name: "Chlorous Acid",
        formula: "HClO<SUB>2</SUB>",
        conjugate: "ClO<SUB>2</SUB><SUP>-</SUP>",
        K: 1.1e-2,
        type: 2,
      },
      {
        name: "Cyanic Acid",
        formula: "HOCN",
        conjugate: "OCN<SUP>-</SUP>",
        K: 3.5e-4,
        type: 2,
      },
      {
        name: "Formic Acid",
        formula: "HCO<SUB>2</SUB>H",
        conjugate: "HCO<SUB>2</SUB><SUP>-</SUP>",
        K: 1.8e-4,
        type: 2,
      },
      {
        name: "Hydrofluoric Acid",
        formula: "HF",
        conjugate: "F<SUP>-</SUP>",
        K: 6.6e-4,
        type: 2,
      },
      {
        name: "Nitrous Acid",
        formula: "HNO<SUB>2</SUB>",
        conjugate: "NO<SUB>2</SUB><SUP>-</SUP>",
        K: 7.2e-4,
        type: 2,
      },
      {
        name: "Hydrazoic Acid",
        formula: "HN<SUB>3</SUB>",
        conjugate: "N<SUB>3</SUB><SUP>-</SUP>",
        K: 1.9e-5,
        type: 2,
      },
      {
        name: "Propionic Acid",
        formula: "C<SUB>3</SUB>H<SUB>6</SUB>O<SUB>2</SUB>",
        conjugate: "C<SUB>3</SUB>H<SUB>5</SUB>O<SUB>2</SUB><SUP>-</SUP>",
        K: 1.3e-5,
        type: 2,
      },
      {
        name: "Hypochlorous Acid",
        formula: "HOCl",
        conjugate: "OCl<SUP>-</SUP>",
        K: 2.9e-8,
        type: 2,
      },
      {
        name: "Dichloroacetic Acid",
        formula: "C<SUB>2</SUB>H<SUB>2</SUB>Cl<SUB>2</SUB>O<SUB>2</SUB>",
        conjugate:
          "C<SUB>2</SUB>H<SUB></SUB>Cl<SUB>2</SUB>O<SUB>2</SUB><SUP>-</SUP>",
        K: 5.5e-2,
        type: 2,
      },
      {
        name: "Thiophenol",
        formula: "C<SUB>6</SUB>H<SUB>5</SUB>SH",
        conjugate: "C<SUB>6</SUB>H<SUB>5</SUB>S<SUP>-</SUP>",
        K: 3.2e-7,
        type: 2,
      },
      {
        name: "Butyric Acid",
        formula: "C<SUB>4</SUB>H<SUB>8</SUB>O<SUB>2</SUB>",
        conjugate: "C<SUB>4</SUB>H<SUB>7</SUB>O<SUB>2</SUB><SUP>-</SUP>",
        K: 1.5e-5,
        type: 2,
      },
      {
        name: "Phenylacetic Acid ",
        formula: "C<SUB>8</SUB>H<SUB>8</SUB>O<SUB>2</SUB>",
        conjugate: "C<SUB>8</SUB>H<SUB>7</SUB>O<SUB>2</SUB><SUP>-</SUP>",
        K: 4.9e-5,
        type: 2,
      },
      {
        name: "Fluoroacetic Acid",
        formula: "C<SUB>2</SUB>H<SUB>3</SUB>FO<SUB>2</SUB>",
        conjugate: "C<SUB>2</SUB>H<SUB>2</SUB>FO<SUB>2</SUB><SUP>-</SUP>",
        K: 2.6e-3,
        type: 2,
      },
      {
        name: "Trichloroacetic Acid",
        formula: "C<SUB>2</SUB>HCl<SUB>3</SUB>O<SUB>2</SUB>",
        conjugate: "C<SUB>2</SUB>Cl<SUB>3</SUB>O<SUB>2</SUB><SUP>-</SUP>",
        K: 0.3,
        type: 2,
      },
      {
        name: "Pyridinium Chloride",
        formula: "C<SUB>5</SUB>H<SUB>5</SUB>NCl",
        conjugate: "C<SUB>5</SUB>H<SUB>4</SUB>NCl<SUP>-</SUP>",
        K: 6.67e-6,
        type: 2,
      },
    ],
    weakBases: [
      {
        name: "Ammonia",
        formula: "NH<SUB>3</SUB>",
        conjugate: "NH<SUB>4</SUB><sup>+</sup>",
        K: 1.8e-5,
        type: 3,
      },
      {
        name: "Aniline",
        formula: "C<SUB>6</SUB>H<SUB>5</SUB>NH<SUB>2</SUB>",
        conjugate: "C<SUB>6</SUB>H<SUB>5</SUB>NH<SUB>3</SUB><sup>+</sup>",
        K: 7.4e-10,
        type: 3,
      },
      {
        name: "Codeine",
        formula: "C<SUB>18</SUB>H<SUB>21</SUB>NO<SUB>3</SUB>",
        conjugate: "C<SUB>18</SUB>H<SUB>22</SUB>NO<SUB>3</SUB><sup>+</sup>",
        K: 8.9e-7,
        type: 3,
      },
      {
        name: "Ethylamine",
        formula: "C<SUB>2</SUB>H<SUB>5</SUB>NH<SUB>2</SUB>",
        conjugate: "C<SUB>2</SUB>H<SUB>5</SUB>NH<SUB>3</SUB><sup>+</sup>",
        K: 4.3e-4,
        type: 3,
      },
      {
        name: "Piperidine",
        formula: "C<SUB>5</SUB>H<SUB>11</SUB>N",
        conjugate: "C<SUB>5</SUB>H<SUB>12</SUB>N<sup>+</sup>",
        K: 1.3e-3,
        type: 3,
      },
      {
        name: "Triethylamine",
        formula: "(C<SUB>2</SUB>H<SUB>5</SUB>)<SUB>3</SUB>N",
        conjugate: "(C<SUB>2</SUB>H<SUB>5</SUB>)<SUB>3</SUB>NH<sup>+</sup>",
        K: 5.2e-4,
        type: 3,
      },
      {
        name: "Trimethylamine",
        formula: "(CH<SUB>3</SUB>)<SUB>3</SUB>N",
        conjugate: "(CH<SUB>3</SUB>)<SUB>3</SUB>NH<sup>+</sup>",
        K: 6.3e-5,
        type: 3,
      },
      {
        name: "Hydroxylamine",
        formula: "NH<SUB>2</SUB>OH",
        conjugate: "NH<SUB>3</SUB>OH<sup>+</sup>",
        K: 9.1e-9,
        type: 3,
      },
      {
        name: "Sodium Cyanide",
        formula: "CN<sup>-</sup>",
        conjugate: "HCN",
        K: 1.61e-5,
        type: 3,
      },
      {
        name: "Potassium Hyprobromide  ",
        formula: "OBr<sup>-</sup>",
        conjugate: "HOBr",
        K: 4e-6,
        type: 3,
      },
      {
        name: "Methylamine",
        formula: "CH<SUB>3</SUB>NH<SUB>2</SUB>",
        conjugate: "CH<SUB>3</SUB>NH<SUB>3</SUB><sup>+</sup>",
        K: 4.2e-4,
        type: 3,
      },
      {
        name: "Morphine",
        formula: "C<SUB>17</SUB>H<SUB>19</SUB>NO<SUB>3</SUB>",
        conjugate: "C<SUB>17</SUB>H<SUB>20</SUB>NO<SUB>3</SUB><sup>+</sup>",
        K: 7.4e-7,
        type: 3,
      },
      {
        name: "Diethylamine",
        formula: "(C<SUB>2</SUB>H<SUB>5</SUB>)<SUB>2</SUB>NH",
        conjugate:
          "(C<SUB>2</SUB>H<SUB>5</SUB>)<SUB>2</SUB>NH<sub>2</sub><sup>+</sup>",
        K: 6.9e-4,
        type: 3,
      },
      {
        name: "Dimethylamine",
        formula: "(CH<SUB>3</SUB>)<SUB>2</SUB>NH  ",
        conjugate: "(CH<SUB>3</SUB>)<SUB>2</SUB>NH<sub>2</sub><sup>+</sup>",
        K: 5.9e-4,
        type: 3,
      },
      {
        name: "Sodium hypoioide",
        formula: "OI<sup>-</sup>",
        conjugate: "HOI",
        K: 4.35e-4,
        type: 3,
      },
      {
        name: "Triethanolamine",
        formula: "C<SUB>6</SUB>H<SUB>15</SUB>NO<SUB>3</SUB>",
        conjugate: "C<SUB>6</SUB>H<SUB>16</SUB>NO<SUB>3</SUB><sup>+</sup>",
        K: 5.8e-7,
        type: 3,
      },
      {
        name: "Pyridine",
        formula: "C<SUB>5</SUB>H<SUB>5</SUB>N",
        conjugate: "C<SUB>5</SUB>H<SUB>6</SUB>N<sup>+</sup>",
        K: 1.5e-9,
        type: 3,
      },
      {
        name: "Hydrazine",
        formula: "N<SUB>2</SUB>H<SUB>4</SUB>",
        conjugate: "N<SUB>2</SUB>H<SUB>5</SUB><sup>+</sup>",
        K: 8.5e-7,
        type: 3,
      },
    ],
    strongBases: [
      {
        name: "Potassium Hydroxide",
        formula: "KOH",
        conjugate: "K<sup>+</sup>",
        K: 1,
        type: 4,
      },
      {
        name: "Sodium hydroxide",
        formula: "NaOH",
        conjugate: "Na<sup>+</sup>",
        K: 1,
        type: 4,
      },
      {
        name: "Cesium Hydroxide",
        formula: "CsOH",
        conjugate: "Cs<sup>+</sup>",
        K: 1,
        type: 4,
      },
      {
        name: "Lithium Hydroxide",
        formula: "LiOH",
        conjugate: "Li<sup>+</sup>",
        K: 1,
        type: 4,
      },
    ],
    neutral: [
      {
        name: "Sodium Nitrate",
        formula: "NaNO<SUB>3</SUB>",
        conjugate: "HNO<SUB>3</SUB>",
        K: 1,
        type: 5,
      },
      {
        name: "Potassium Chloride",
        formula: "KCl",
        conjugate: "HCl",
        K: 1,
        type: 5,
      },
      { name: "Cesium Iodide", formula: "CsI", conjugate: "HI", K: 1, type: 5 },
      {
        name: "Calcium Bromide",
        formula: "CaBr<SUB>2</SUB>",
        conjugate: "HBr",
        K: 1,
        type: 5,
      },
    ],
  };
  cp.getRandomAcidOrBase = (type) => {
    const list = acidBaseList[type];
    if (!list) return null;
    const idx = cp.Random.int(0, list.length - 1);
    return list[idx];
  };
})((window.cp = window.cp || {}));
